const assert = require('node:assert/strict');
module.exports = async page => {
  await page.evaluate(()=>{window.menuOriginalViewport=document.querySelector('.compare-image-button');window.menuOriginalImage=window.menuOriginalViewport?.querySelector('img');});
  const more = page.locator('.track-more-button').first();
  await more.focus(); await page.keyboard.press('Enter');
  assert.equal(await page.locator('.track-menu').isVisible(),true);
  await page.keyboard.press('ArrowDown');
  assert.equal(await page.evaluate(()=>document.activeElement.textContent),'重命名前缀');
  await page.keyboard.press('Escape');
  assert.equal(await more.evaluate(el=>document.activeElement===el),true);
  await more.click();
  await page.locator('.track-menu .danger-button').click();
  assert.equal(await page.locator('.track-menu .danger-button').textContent(),'确定');
  await page.keyboard.press('Escape');
  assert.equal(await page.evaluate(()=>state.pendingDelete.type),'');
  assert.equal(await page.evaluate(()=>document.querySelector('.compare-image-button')===window.menuOriginalViewport&&document.querySelector('.compare-image-button img')===window.menuOriginalImage),true,'menus preserve the original image node');
  await more.click();
  assert.equal(await page.locator('.track-menu .danger-button').textContent(),'删除轨道');
  await page.evaluate(()=>elements.railBoard.dispatchEvent(new Event('scroll')));
  assert.equal(await page.locator('.track-menu').isVisible(),false);
  await more.click();
  await page.locator('.track-menu button').first().click();
  await page.locator('#renameInput').fill('视觉检查轨道');
  await page.locator('#confirmRenameButton').click();
  await page.waitForFunction(()=>state.project.tracks[0].name==='视觉检查轨道');
  await more.click();
  await page.locator('.track-menu button').nth(1).click();
  await page.locator('#renameInput').fill('UI');
  await page.locator('#confirmRenameButton').click();
  await page.waitForFunction(()=>state.project.tracks[0].prefix==='UI');
  await page.evaluate(async()=>{createTrack();await waitForProjectOperations();});
  const count = await page.locator('.track-more-button').count();
  await page.locator('.track-more-button').last().click();
  await page.locator('.track-menu .danger-button').click();
  await page.locator('.track-menu .danger-button').click();
  await page.waitForFunction(count=>state.project.tracks.length===count-1,count);
  const locked = await page.evaluate(()=>{state.importBatch={};updateImportControls();const result=elements.tracks.querySelector('.track-more-button').disabled;state.importBatch=null;updateImportControls();return result;});
  assert.equal(locked,true);
  await page.locator('.track-more-button').first().click();
  const fits = await page.locator('.track-menu').evaluate(el=>{const r=el.getBoundingClientRect();return r.x>=0&&r.y>=0&&r.right<=innerWidth&&r.bottom<=innerHeight;});
  assert.equal(fits,true);
  await page.keyboard.press('Escape');
};
